const Map<String, String> appStringsVi = {
  'appName': 'Focus Forest',
  'appTagline': 'Pomodoro — trồng rừng mỗi khi tập trung',
  'splashLoading': 'Đang mọc rừng...',
  'onboardingTitle1': 'Tập trung 25 phút',
  'onboardingDesc1': 'Bắt đầu phiên Pomodoro và giữ tập trung. Mỗi phiên hoàn thành giúp một cây mọc trong rừng của bạn.',
  'onboardingTitle2': 'Theo dõi tiến độ',
  'onboardingDesc2': 'Xem tổng thời gian học, thống kê hàng ngày, chuỗi ngày và bộ sưu tập rừng đang lớn.',
  'onboardingTitle3': 'Kiếm sao & tùy chỉnh',
  'onboardingDesc3': 'Kiếm sao miễn phí khi tập trung hàng ngày, hoặc mua gói sao qua Google Play. Mở khóa kiểu cây, theme, hình nền và tính năng premium.',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',
  'navFocus': 'Tập trung',
  'navForest': 'Rừng',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'focusTitle': 'Tập trung',
  'forestTitle': 'Rừng của tôi',
  'forestSubtitle': 'Thống kê thời gian học',
  'phaseFocus': 'Phiên tập trung',
  'phaseShortBreak': 'Nghỉ ngắn',
  'phaseLongBreak': 'Nghỉ dài',
  'timerRunning': 'Giữ tập trung...',
  'timerPaused': 'Đã tạm dừng',
  'timerCompleted': 'Hoàn thành phiên!',
  'timerReady': 'Sẵn sàng tập trung',
  'startFocus': 'Bắt đầu',
  'pause': 'Tạm dừng',
  'resume': 'Tiếp tục',
  'stop': 'Dừng',
  'skipBreak': 'Bỏ qua nghỉ',
  'whiteNoise': 'White noise',
  'statsOverview': 'Tổng quan',
  'statTotalTime': 'Tổng thời gian',
  'statTodayTime': 'Hôm nay',
  'statTotalSessions': 'Phiên hoàn thành',
  'statTrees': 'Cây đã trồng',
  'statStreak': 'Chuỗi ngày',
  'recentSessions': 'Phiên gần đây',
  'noSessionsYet': 'Chưa có phiên nào. Hoàn thành phiên tập trung đầu tiên để trồng cây!',
  'sessionCompleted': 'Phiên tập trung',
  'minutesValue': '{count} phút',
  'daysValue': '{count} ngày',
  'adPlaceholder': 'Quảng cáo — Gỡ quảng cáo trong Cửa hàng',
  'settingsTitle': 'Cài đặt',
  'settingsSubtitle': 'Tùy chọn & giao diện',
  'activeCustomization': 'Giao diện đang dùng',
  'activeTheme': 'Theme',
  'activeBackground': 'Hình nền',
  'activeSkin': 'Kiểu cây',
  'appearance': 'Giao diện',
  'darkMode': 'Chế độ tối',
  'premiumFeatures': 'Premium',
  'exportStats': 'Xuất thống kê',
  'exportStatsDesc': 'Chia sẻ thống kê dạng văn bản',
  'exportDone': 'Đã xuất thống kê!',
  'exportLocked': 'Mở khóa xuất dữ liệu trong Cửa hàng',
  'exportTitle': 'Thống kê Focus Forest',
  'exportRecentSessions': 'Phiên gần đây:',
  'other': 'Khác',
  'language': 'Ngôn ngữ',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'openShop': 'Mở Cửa hàng',
  'openShopDesc': 'Mua sao, theme & tính năng',
  'privacyPolicy': 'Chính sách bảo mật',
  'copyright': '© Focus Forest. Dữ liệu lưu cục bộ trên thiết bị.',
  'themeDefault': 'Mặc định',
  'bgDefault': 'Mặc định',
  'skinDefault': 'Mặc định',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Sao, theme & tính năng premium',
  'shopBalance': 'Sao của bạn',
  'shopBuyStars': 'Mua sao',
  'shopBuyStarsDesc': 'Mua thêm sao qua Google Play',
  'shopEarnStars': 'Kiếm sao',
  'shopDailyReward': 'Thưởng hàng ngày',
  'shopDailyRewardDesc': 'Nhận {amount} sao mỗi ngày',
  'shopClaim': 'Nhận',
  'shopClaimed': 'Đã nhận hôm nay',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuBackgrounds': 'Hình nền',
  'shopMenuSkins': 'Kiểu cây',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có mục trong danh mục này',
  'shopOwned': 'Đã sở hữu',
  'shopActive': 'Đang dùng',
  'shopApply': 'Áp dụng',
  'shopResetDefault': 'Về mặc định',
  'shopBuy': 'Mua',
  'shopPrice': '{price} sao',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Trải nghiệm không quảng cáo vĩnh viễn',
  'shopThemeSunset': 'Hoàng hôn',
  'shopThemeSunsetDesc': 'Tông cam ấm hoàng hôn',
  'shopThemeOcean': 'Đại dương',
  'shopThemeOceanDesc': 'Tông xanh dịu cho tập trung',
  'shopThemeAurora': 'Cực quang',
  'shopThemeAuroraDesc': 'Theme tím cực quang premium',
  'shopThemeCherry': 'Hoa anh đào',
  'shopThemeCherryDesc': 'Theme hồng mùa xuân',
  'shopBgMeadow': 'Đồng cỏ xanh',
  'shopBgMeadowDesc': 'Gradient rừng xanh tươi',
  'shopBgSunset': 'Hoàng hôn vàng',
  'shopBgSunsetDesc': 'Gradient hoàng hôn ấm',
  'shopBgNight': 'Rừng đêm',
  'shopBgNightDesc': 'Gradient rừng đêm sâu',
  'shopBgSpring': 'Mùa xuân',
  'shopBgSpringDesc': 'Gradient mùa xuân tươi',
  'shopSkinOak': 'Cây sồi',
  'shopSkinOakDesc': 'Kiểu cây sồi cổ điển',
  'shopSkinPine': 'Cây thông',
  'shopSkinPineDesc': 'Kiểu cây thông cao',
  'shopSkinSakura': 'Anh đào',
  'shopSkinSakuraDesc': 'Cây hoa anh đào đẹp',
  'shopSkinBamboo': 'Tre trúc',
  'shopSkinBambooDesc': 'Kiểu tre zen',
  'shopFeatCustomTimer': 'Hẹn giờ tùy chỉnh',
  'shopFeatCustomTimerDesc': 'Chọn phiên 15, 25, 45 hoặc 60 phút',
  'shopFeatLongBreak': 'Nghỉ dài',
  'shopFeatLongBreakDesc': 'Mở khóa nghỉ 15 phút',
  'shopFeatWhiteNoise': 'White noise',
  'shopFeatWhiteNoiseDesc': 'Âm thanh nền khi tập trung',
  'shopFeatStatsExport': 'Xuất thống kê',
  'shopFeatStatsExportDesc': 'Xuất lịch sử tập trung',
  'shopFeatNoWatermark': 'Không watermark',
  'shopFeatNoWatermarkDesc': 'Xuất sạch không logo',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại. Thử lại.',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'coinsAdded': 'Đã thêm sao vào ví!',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'dailyRewardClaimed': 'Đã nhận thưởng hàng ngày!',
  'focusSessionRewardEarned': 'Nhận sao khi hoàn thành phiên tập trung!',
  'streakBonusEarned': 'Thưởng chuỗi ngày!',
  'billingDisabled': 'Google Play tạm không khả dụng. Kiếm sao bằng cách tập trung!',
  'configNetworkError': 'Không kết nối được server — dùng cài đặt đã lưu',
  'configTimeout': 'Hết thời gian chờ — dùng cài đặt đã lưu',
  'coinPackTitle': 'Mua sao',
  'coinPackSubtitle': 'Chọn gói sao',
  'restorePurchases': 'Khôi phục mua hàng',
  'privacyTitle': 'Chính sách bảo mật',
  'privacyIntro': 'Focus Forest lưu mọi dữ liệu cục bộ trên thiết bị. Chúng tôi không thu thập, truyền hay bán thông tin cá nhân.',
  'privacyData': 'Phiên tập trung và cài đặt không rời thiết bị trừ khi bạn chủ động xuất.',
  'privacyContact': 'Liên hệ: support@focusforest.app',
  'yourWallet': 'Ví của bạn',
  'coinsLabel': 'Sao',
  'buyCoins': 'Mua sao',
  'buyCoinsDesc': 'Mua gói sao qua Google Play',
  'yourCoins': 'Bạn có {count} sao',
  'shopClaimedDaily': 'Đã nhận hôm nay',
  'shopClaimDaily': 'Nhận',
  'earnStepFocus': 'Hoàn thành phiên',
  'earnStepFocusDesc': '+5 sao/phiên (tối thiểu 20 phút, max 12/ngày)',
  'starRewardHint': 'Hoàn thành ít nhất 20 phút để nhận sao và trồng cây',
  'earnStepStreak': 'Thưởng chuỗi',
  'earnStepStreakDesc': '+15 sao mỗi 4 phiên',
  'earnStepDaily': 'Đăng nhập hàng ngày',
  'earnStepDailyDesc': '+10 sao mỗi ngày',
  'buyWithGooglePlay': 'Mua qua Google Play',
  'shopBrowse': 'Danh mục',
  'apply': 'Áp dụng',
  'applied': 'Đã áp dụng!',
  'resetDefault': 'Về mặc định',
  'resetToDefault': 'Về mặc định',
  'owned': 'Đã sở hữu',
  'openingBilling': 'Đang mở Google Play...',
  'removeAdsIap': 'Gỡ quảng cáo qua Google Play',
  'processingPurchase': 'Đang xử lý...',
  'billingUnavailable': 'Thanh toán không khả dụng',
  'productsNotFound': 'Không tìm thấy sản phẩm',
  'earnCoinsHint': 'Kiếm sao bằng phiên tập trung hoặc thưởng hàng ngày',
  'coinPack': 'Gói sao {num}',
  'coinAmount': '{count} sao',
  'coinRewardSub': 'Số dư: {balance} sao',
  'justNow': 'Vừa xong',
  'ago': '{time} trước',
  'tagStudy': 'Học',
  'tagWork': 'Làm việc',
  'tagRead': 'Đọc',
  'tagOther': 'Khác',
  'dailyGoal': 'Mục tiêu hôm nay',
  'goalProgress': '{done}/{goal} phút',
  'goalReached': 'Đã đạt mục tiêu!',
  'weekActivity': '7 ngày gần đây',
  'myGrove': 'Khu rừng',
  'achievements': 'Thành tựu',
  'achLocked': 'Chưa mở',
  'achFirstTitle': 'Cây đầu tiên',
  'achFirstDesc': 'Hoàn thành 1 phiên tập trung',
  'achTreesTitle': 'Tiểu lâm viên',
  'achTreesDesc': 'Trồng 10 cây',
  'achStreak3Title': '3 ngày liên tục',
  'achStreak3Desc': 'Giữ streak 3 ngày',
  'achStreak7Title': 'Một tuần tập trung',
  'achStreak7Desc': 'Giữ streak 7 ngày',
  'achHourTitle': 'Giờ đầu tiên',
  'achHourDesc': 'Tổng 60 phút tập trung',
  'achGoalTitle': 'Đủ chỉ tiêu',
  'achGoalDesc': 'Đạt mục tiêu phút hôm nay',
  'statWeek': 'Tuần này',
  'statBestDay': 'Ngày tốt nhất',
  'timerSettings': 'Timer',
  'focusLength': 'Thời lượng tập trung',
  'shortBreak': 'Nghỉ ngắn',
  'longBreak': 'Nghỉ dài',
  'dailyGoalSetting': 'Mục tiêu mỗi ngày',
};
