const Map<String, String> appStringsEn = {
  'appName': 'Focus Forest',
  'appTagline': 'Pomodoro timer — grow your forest with every focus session',
  'splashLoading': 'Growing your forest...',
  'onboardingTitle1': '25-minute focus',
  'onboardingDesc1': 'Start a Pomodoro session and stay focused. Every completed session helps a new tree grow in your forest.',
  'onboardingTitle2': 'Track your progress',
  'onboardingDesc2': 'See total study time, daily stats, streaks and your growing forest collection.',
  'onboardingTitle3': 'Earn stars & customize',
  'onboardingDesc3': 'Earn free stars by focusing daily, or buy star packs via Google Play. Unlock tree skins, themes, backgrounds and premium features.',
  'getStarted': 'Get started',
  'skip': 'Skip',
  'next': 'Next',
  'navFocus': 'Focus',
  'navForest': 'Forest',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'focusTitle': 'Focus',
  'forestTitle': 'My Forest',
  'forestSubtitle': 'Your focus statistics',
  'phaseFocus': 'Focus session',
  'phaseShortBreak': 'Short break',
  'phaseLongBreak': 'Long break',
  'timerRunning': 'Stay focused...',
  'timerPaused': 'Paused',
  'timerCompleted': 'Session complete!',
  'timerReady': 'Ready to focus',
  'startFocus': 'Start focus',
  'pause': 'Pause',
  'resume': 'Resume',
  'stop': 'Stop',
  'skipBreak': 'Skip break',
  'whiteNoise': 'White noise',
  'statsOverview': 'Overview',
  'statTotalTime': 'Total focus time',
  'statTodayTime': 'Today',
  'statTotalSessions': 'Sessions completed',
  'statTrees': 'Trees grown',
  'statStreak': 'Day streak',
  'recentSessions': 'Recent sessions',
  'noSessionsYet': 'No sessions yet. Complete your first focus session to grow a tree!',
  'sessionCompleted': 'Focus session',
  'minutesValue': '{count} min',
  'daysValue': '{count} days',
  'adPlaceholder': 'Ad — Remove ads in Shop',
  'settingsTitle': 'Settings',
  'settingsSubtitle': 'Preferences & customization',
  'activeCustomization': 'Active look',
  'activeTheme': 'Theme',
  'activeBackground': 'Background',
  'activeSkin': 'Tree style',
  'appearance': 'Appearance',
  'darkMode': 'Dark mode',
  'premiumFeatures': 'Premium',
  'exportStats': 'Export statistics',
  'exportStatsDesc': 'Share your focus stats as text',
  'exportDone': 'Stats exported!',
  'exportLocked': 'Unlock export in Shop',
  'exportTitle': 'Focus Forest Stats',
  'exportRecentSessions': 'Recent sessions:',
  'other': 'Other',
  'language': 'Language',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'openShop': 'Open Shop',
  'openShopDesc': 'Buy stars, themes & features',
  'privacyPolicy': 'Privacy policy',
  'copyright': '© Focus Forest. All data stored locally on your device.',
  'themeDefault': 'Default',
  'bgDefault': 'Default',
  'skinDefault': 'Default',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Stars, themes & premium features',
  'shopBalance': 'Your stars',
  'shopBuyStars': 'Buy stars',
  'shopBuyStarsDesc': 'Get more stars via Google Play',
  'shopEarnStars': 'Earn stars',
  'shopDailyReward': 'Daily reward',
  'shopDailyRewardDesc': 'Claim {amount} stars once per day',
  'shopClaim': 'Claim',
  'shopClaimed': 'Claimed today',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Tree styles',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'shopOwned': 'Owned',
  'shopActive': 'Active',
  'shopApply': 'Apply',
  'shopResetDefault': 'Reset to default',
  'shopBuy': 'Buy',
  'shopPrice': '{price} stars',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Enjoy an ad-free experience forever',
  'shopThemeSunset': 'Sunset Grove',
  'shopThemeSunsetDesc': 'Warm orange sunset tones',
  'shopThemeOcean': 'Ocean Breeze',
  'shopThemeOceanDesc': 'Cool blue tones for calm focus',
  'shopThemeAurora': 'Aurora Night',
  'shopThemeAuroraDesc': 'Purple aurora premium look',
  'shopThemeCherry': 'Cherry Blossom',
  'shopThemeCherryDesc': 'Soft pink spring theme',
  'shopBgMeadow': 'Green Meadow',
  'shopBgMeadowDesc': 'Lush forest gradient',
  'shopBgSunset': 'Golden Sunset',
  'shopBgSunsetDesc': 'Warm sunset gradient',
  'shopBgNight': 'Night Forest',
  'shopBgNightDesc': 'Deep night forest gradient',
  'shopBgSpring': 'Spring Bloom',
  'shopBgSpringDesc': 'Fresh spring gradient',
  'shopSkinOak': 'Oak Tree',
  'shopSkinOakDesc': 'Classic strong oak style',
  'shopSkinPine': 'Pine Tree',
  'shopSkinPineDesc': 'Tall evergreen pine style',
  'shopSkinSakura': 'Sakura Tree',
  'shopSkinSakuraDesc': 'Beautiful cherry blossom tree',
  'shopSkinBamboo': 'Bamboo',
  'shopSkinBambooDesc': 'Zen bamboo tree style',
  'shopFeatCustomTimer': 'Custom timer',
  'shopFeatCustomTimerDesc': 'Choose 15, 25, 45 or 60 minute sessions',
  'shopFeatLongBreak': 'Long break',
  'shopFeatLongBreakDesc': 'Unlock 15-minute long breaks',
  'shopFeatWhiteNoise': 'White noise',
  'shopFeatWhiteNoiseDesc': 'Ambient sounds during focus',
  'shopFeatStatsExport': 'Export statistics',
  'shopFeatStatsExportDesc': 'Export your focus history',
  'shopFeatNoWatermark': 'No watermark',
  'shopFeatNoWatermarkDesc': 'Clean exports without branding',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed. Try again.',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'coinsAdded': 'Stars added to your balance!',
  'removeAdsUnlocked': 'Ads removed!',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'focusSessionRewardEarned': 'Stars earned for completing a focus session!',
  'streakBonusEarned': 'Streak bonus stars earned!',
  'billingDisabled': 'Google Play billing is temporarily unavailable. Earn stars by focusing!',
  'configNetworkError': 'Could not reach server — using cached settings',
  'configTimeout': 'Server timeout — using cached settings',
  'coinPackTitle': 'Buy stars',
  'coinPackSubtitle': 'Choose a star pack',
  'restorePurchases': 'Restore purchases',
  'privacyTitle': 'Privacy Policy',
  'privacyIntro': 'Focus Forest stores all your data locally on your device. We do not collect, transmit or sell your personal information.',
  'privacyData': 'Your focus sessions and settings never leave your device unless you explicitly export them.',
  'privacyContact': 'Contact: support@focusforest.app',
  'yourWallet': 'Your wallet',
  'coinsLabel': 'Stars',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': 'Get star packs via Google Play',
  'yourCoins': 'You have {count} stars',
  'shopClaimedDaily': 'Claimed today',
  'shopClaimDaily': 'Claim',
  'earnStepFocus': 'Complete focus',
  'earnStepFocusDesc': '+5 stars per session (min 20 min, max 12/day)',
  'starRewardHint': 'Complete at least 20 minutes to earn stars and grow a tree',
  'earnStepStreak': 'Streak bonus',
  'earnStepStreakDesc': '+15 stars every 4 sessions',
  'earnStepDaily': 'Daily login',
  'earnStepDailyDesc': '+10 stars once per day',
  'buyWithGooglePlay': 'Buy with Google Play',
  'shopBrowse': 'Categories',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Reset default',
  'resetToDefault': 'Reset to default',
  'owned': 'Owned',
  'openingBilling': 'Opening Google Play...',
  'removeAdsIap': 'Remove ads via Google Play',
  'processingPurchase': 'Processing purchase...',
  'billingUnavailable': 'Billing unavailable on this device',
  'productsNotFound': 'Products not found in store',
  'earnCoinsHint': 'Earn stars by completing focus sessions or claim daily reward',
  'coinPack': 'Star pack {num}',
  'coinAmount': '{count} stars',
  'coinRewardSub': 'Balance: {balance} stars',
  'justNow': 'Just now',
  'ago': '{time} ago',
  'tagStudy': 'Study',
  'tagWork': 'Work',
  'tagRead': 'Read',
  'tagOther': 'Other',
  'dailyGoal': 'Today’s goal',
  'goalProgress': '{done}/{goal} min',
  'goalReached': 'Goal reached!',
  'weekActivity': 'Last 7 days',
  'myGrove': 'Your grove',
  'achievements': 'Achievements',
  'achLocked': 'Locked',
  'achFirstTitle': 'First tree',
  'achFirstDesc': 'Complete one focus session',
  'achTreesTitle': 'Little grove',
  'achTreesDesc': 'Grow 10 trees',
  'achStreak3Title': '3-day streak',
  'achStreak3Desc': 'Focus 3 days in a row',
  'achStreak7Title': 'Week warrior',
  'achStreak7Desc': 'Keep a 7-day streak',
  'achHourTitle': 'First hour',
  'achHourDesc': 'Reach 60 total minutes',
  'achGoalTitle': 'On target',
  'achGoalDesc': 'Hit today’s minute goal',
  'statWeek': 'This week',
  'statBestDay': 'Best day',
  'timerSettings': 'Timer',
  'focusLength': 'Focus length',
  'shortBreak': 'Short break',
  'longBreak': 'Long break',
  'dailyGoalSetting': 'Daily goal',
};
